### PR TITLE
Update README.md by Piumal Kulasekara

### PR DESCRIPTION
**Pull request by piumalkulasekara**

### CODE REVIEW

**Comment by lordadamson** [comment]
Hi and thank you for the resource addition.
I've got two points:
* To create a link you use the following syntax: `[link text](http://actual.link)` So you missed the square brackets.
* The learning resources are now taking a lot of space. How about we move them to a separate file and link to them instead?

**Comment by piumalkulasekara** [comment]
yes. that is a great idea. So should I named the new file as LearningResources.md ?

**Comment by lordadamson** [comment]
yes sir that sounds good :D

**Comment by piumalkulasekara** [comment]
I have added the file. please review and merge it

**Comment by lordadamson** [comment]
Done

**Pull request closed without merging**
