### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by sa3diya**
15-sa3diya :v :v </br>

### CODE REVIEW

**Comment by lordadamson** [comment]
@sa3diya you created a new file called "hosh" and added you name in it...
that's not what you're supposed to do. you're supposed to modify the README.md file and add your name to it.

**Comment by 2n0n** [comment]
ana 7ass any 5aby gedaaan :D :D

**Comment by TaiSoNNN** [comment]
hhhhhhhhhhhh esmha 8abby ya Bby :v @2n0n

**Comment by sa3diya** [comment]
@lordadamson  don't knou how :'( what's after clone !

**Comment by lordadamson** [comment]
efta7e el file b notepad ya @sa3diya w deefe esmek feeh :D

**Pull request closed without merging**
