### PR TITLE
 Tan Function is Done

### PR DESCRIPTION
**Pull request by alsawaf**
Tan Function is Done ;)

### CODE REVIEW

**Comment by lordadamson** [comment]
I asked for a tan function. Why am I getting a subtract function?

**Comment by alsawaf** [comment]
How !! , i did make a tan function !

2015-12-10 19:22 GMT+02:00 Adam Zahran <notifications@github.com>:

**Comment by lordadamson** [comment]
screenshot_2015-12-11-09-57-45

**Comment by lordadamson** [comment]
screenshot_2015-12-11-09-57-45

**Comment by alsawaf** [comment]
tyb ma l satr ely bloon al a7mar dah ely ana ms7to we katb mkano l satr ely
be l loon al a5dar , y3ny 3ndy l satr l a7mar dah mesh bayn asln !!


2015-12-11 10:43 GMT+02:00 Adam Zahran <notifications@github.com>:

**Comment by lordadamson** [comment]
7abeebe maho el satr ele bel a5dr da bardo el function esmaha subtract :'D

**Pull request closed without merging**
