### PR TITLE
Create Amany Helmy

### PR DESCRIPTION
**Pull request by amanyhelmy5**

### CODE REVIEW

**Comment by lordadamson** [comment]
why did you close it?

**Comment by amanyhelmy5** [comment]
Iam very sorry,Idid it by mistake.
 I wont to join you ,and  practice in your calculator program,but I don not
know more about git.

**Comment by lordadamson** [comment]
Good job :D your name was added to the list.

I have another challenge for you:
there is a branch called `trainingproject`. It's a simple command line calculator that we're making to practice more on git.
I want you to add a function called 'square'. It simply takes a number and raise it to the power of two.
example: `square(3)` would return `9`.

good luck :D

**Comment by amanyhelmy5** [comment]
ok,Thanks for you ;)

**Pull request merged**
